### ISSUE TITLE
Build output includes references to process.env making the output JS unable to be embedded in webpages

### ISSUE THREAD

**Issue by subins2000** [AndrewBastin/vue3-embedded-library-template#1]
Steps to reproduce:

* git clone this template
* Optionally add `iife` to `formats` in `vite.config.ts`
* `npm i && npm run build`
* See output `dist/*.js` files
* You can find references to "process.env"

Embedding the output JS in webpage doesn't work because of this `process.env` reference. Removing vue imports (or removing vue as a dependency) fixes this problem.

Another way is to make a dummy `window.process` object before loading the script but that's redundant.

<img width="1435" alt="Screenshot 2023-07-15 at 2 40 41 PM" src="https://github.com/AndrewBastin/vue3-embedded-library-template/assets/2305675/fb87fe6e-018c-441b-8afc-43af543ae564">

**Comment by AndrewBastin** [comment]
Fixed as of c4a7edd
